{% set version = "0.0.1" %}

package:
  name: "homoeditdistance"
  version: "{{ version }}"

source:
  git_url: https://github.com/AlBi-HHU/homo-edit-distance.git
  git_rev: "{{ version }}"

build:
  noarch: python
  entry_points:
    - hed=homoeditdistance.demonstration:main
  script: "{{ PYTHON }} setup.py install"

requirements:
  host:
    - numpy
    - setuptools
    - python
  run:
    - numpy
    - python

test:
  imports:
    - homoeditdistance
    - homoeditdistance.tests
  commands:
    - hed --help

about:
  home: "https://github.com/AlBi-HHU/homo-edit-distance"
  license: MIT
  license_file: LICENSE
  summary: "An implementation of the homo-edit distance algorithm."
  description: "A homo-insertion is an insertion of a string of equal characters, which we also call a block, into another string. A homo-deletion is the inverse operation, that is, the deletion of such a block. We consider the following problem: Given two strings, what is the minimum number of homo-insertions or homo-deletions needed to convert one into the other? We refer to this number as the homo-edit distance."

extra:
  recipe-maintainers:
    - AlBi-HHU

